services:
  database:
    image: postgres:latest
    container_name: postgres-container-dev
    restart: always
    environment:
      POSTGRES_DB: currency
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - currency-db-data-local:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  currency-db-data-local: