services:
  backend:
    container_name: currency_service
    build:
      context: ../
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: jdbc:postgresql://database:5432/currency
      DATABASE_USERNAME: dbuser
      DATABASE_PASSWORD: dbpassword
      EXCHANGE_API_KEY: <place your Exchange API KEY Here>
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - app_network_backend

  database:
    image: postgres:latest
    container_name: postgres-currency-container
    restart: unless-stopped
    environment:
      POSTGRES_DB: currency
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - currency-db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - app_network_backend

networks:
  app_network_backend:
    driver: bridge
volumes:
  currency-db-data: